name: Rsync Deploy

on:
  push:
    branches:
      - main  # Or your deployment branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan staging.rmslabs.dev >> ~/.ssh/known_hosts

    - name: Rsync files
      run: |
        rsync -avz --exclude='.git*' ./ mattvanderpol_com@staging.rmslabs.dev:./files/wp-content/themes/mattvanderpol-com-2024/

